### ISSUE TITLE
Todo for next release

### ISSUE THREAD

**Issue by kaat0** [railtoolkit/schema#22]
- [ ] allow for functions in train acceleration values 
- [ ] rename `rotation_mass` in factor for empty vehicle
- [ ] `rolling_resistance` should be a part of `base_resistance`, why does it exist? -> explain A,B and C!
- [ ] add switch for A  + B v + C v v formula vs. actually resistance calculations
- [ ] allow for speed\force array in resistance
- [ ] specify the difference of traction at wheelbase vs. at hook and which one is used
